[flavor]
dark = "gruvbox-dark-material"

[tabs]
active = { fg = "#1d2021", bg = "#a89984" }
inactive = { fg = "#a89984", bg = "reset" }

[mode]
normal_main = { fg = "#1d2021", bg = "#a89984", bold = true }
normal_alt = { fg = "#a89984", bg = "#3c3836" }
select_main = { fg = "#1d2021", bg = "#d65d0e", bold = true }
select_alt = { fg = "#a89984", bg = "#3c3836" }
unset_main = { fg = "#1d2021", bg = "#d79921", bold = true }
unset_alt = { fg = "#a89984", bg = "#3c3836" }

[status]
progress_normal = { fg = "#3c3836", bg = "#282828" }
progress_error = { fg = "#cc241d", bg = "#282828" }

[which]
mask = { bg = "reset" }

[help]
footer = { fg = "#282828", bg = "#a89984" }
