general {
    # lock_cmd = notify-send "lock!"          # dbus/sysd lock command (loginctl lock-session) 
    # unlock_cmd = notify-send "unlock!"      # same as above, but unlock
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    lock_cmd = pidof hyprlock || env DBUS_SESSION_BUS_ADDRESS="$DBUS_SESSION_BUS_ADDRESS" HYPRLAND_INSTANCE_SIGNATURE="$HYPRLAND_INSTANCE_SIGNATURE" XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" hyprlock -c /home/chief/.config/hypr/hyprlock.conf # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# Screenlock
listener {
    timeout = 180                            # in seconds
    on-timeout = env DBUS_SESSION_BUS_ADDRESS="$DBUS_SESSION_BUS_ADDRESS" HYPRLAND_INSTANCE_SIGNATURE="$HYPRLAND_INSTANCE_SIGNATURE" XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" hyprlock -c /home/chief/.config/hypr/hyprlock.conf # command to run when timeout has passed
    # on-resume = notify-send "Welcome back to your desktop!"  # command to run when activity is detected after timeout has fired.
}

# Suspend
listener {
    timeout = 360                            # in seconds
    on-timeout = systemctl suspend # command to run when timeout has passed
    # on-resume = notify-send "Welcome back to your desktop!"  # command to run when activity is detected after timeout has fired.
}
