#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
# exec-once = ~/.config/waybar/scripts/launch.sh

exec-once = hyprctl setcursor Bibata Modern Classic 24

exec-once = awww-daemon &
exec-once = bash -lc 'wall="$HOME/Pictures/Wallpapers/baby-yoda.png"; [ -e "$HOME/.current_wallpaper" ] && wall="$(readlink -f "$HOME/.current_wallpaper")"; swww img "$wall" --transition-type wipe'
exec-once = hypridle &
exec-once = waybar &
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent &

exec-once = swaync &

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = wl-clip-persist --clipboard regular
